name: build and test

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual run'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
        - Blazor.SourceGenerators
        - Blazor.Serialization
        - Blazor.LocalStorage.WebAssembly
        - Blazor.LocalStorage
        - Blazor.SessionStorage.WebAssembly
        - Blazor.SessionStorage
        - Blazor.Geolocation.WebAssembly
        - Blazor.Geolocation
        - Blazor.SpeechSynthesis.WebAssembly
        - Blazor.SpeechSynthesis
        - Blazor.SpeechRecognition.WebAssembly
        - Blazor.SpeechRecognition
    steps:
    - uses: actions/checkout@v2

    - name: 'Print manual run reason'
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        echo 'Reason: ${{ github.event.inputs.reason }}'
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true

    - name: Restore dependencies for ${{ matrix.project }}
      run: |
        dotnet restore ./src/${{ matrix.project }}/${{ matrix.project }}.csproj
      
    - name: Build ${{ matrix.project }}
      run: |
        dotnet build ./src/${{ matrix.project }}/${{ matrix.project }}.csproj --configuration Release --no-restore

  test:
    name: test
    runs-on: ubuntu-latest
    needs: build

    steps:    
    - uses: actions/checkout@v2
    
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true

    - name: Run tests
      run: |
        dotnet test ./tests/Blazor.SourceGenerators.Tests/Blazor.SourceGenerators.Tests.csproj --verbosity normal
