name: pull request

on:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.json'
    - '**.csproj'
    - '**.sln'

jobs:
  validate:
    name: validate
    uses: ./.github/workflows/build-validation.yml